"""esquema inicial

Revision ID: d0c2f5902e02
Revises: 
Create Date: 2026-07-03 14:34:08.712460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c2f5902e02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidades_financieras',
    sa.Column('id_entidad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_entidad', sa.String(length=30), nullable=False),
    sa.Column('tasa_base', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_entidad')
    )
    op.create_index(op.f('ix_entidades_financieras_id_entidad'), 'entidades_financieras', ['id_entidad'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('vehiculos',
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_vehiculo')
    )
    op.create_index(op.f('ix_vehiculos_id_vehiculo'), 'vehiculos', ['id_vehiculo'], unique=False)
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ingresos_mensuales', sa.Float(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_index(op.f('ix_clientes_dni'), 'clientes', ['dni'], unique=True)
    op.create_index(op.f('ix_clientes_id_cliente'), 'clientes', ['id_cliente'], unique=False)
    op.create_table('creditos_vehiculares',
    sa.Column('id_credito', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_entidad', sa.Integer(), nullable=False),
    sa.Column('cuota_inicial', sa.Float(), nullable=False),
    sa.Column('monto_financiado', sa.Float(), nullable=False),
    sa.Column('tipo_moneda', sa.String(length=3), nullable=False),
    sa.Column('tipo_tasa', sa.String(length=20), nullable=False),
    sa.Column('tasa_interes', sa.Float(), nullable=False),
    sa.Column('frecuencia_capitalizacion', sa.String(length=20), nullable=True),
    sa.Column('plazo_meses', sa.Integer(), nullable=False),
    sa.Column('tipo_gracia', sa.String(length=10), nullable=False),
    sa.Column('meses_gracia', sa.Integer(), nullable=False),
    sa.Column('cuota_balon_pct', sa.Float(), nullable=False),
    sa.Column('seguro_vehicular_mensual', sa.Float(), nullable=False),
    sa.Column('seguro_desgravamen_mensual', sa.Float(), nullable=False),
    sa.Column('gastos_administrativos', sa.Float(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_entidad'], ['entidades_financieras.id_entidad'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculos.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_credito')
    )
    op.create_index(op.f('ix_creditos_vehiculares_id_credito'), 'creditos_vehiculares', ['id_credito'], unique=False)
    op.create_table('cuotas',
    sa.Column('id_cuota', sa.Integer(), nullable=False),
    sa.Column('id_credito', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('cuota', sa.Float(), nullable=False),
    sa.Column('interes', sa.Float(), nullable=False),
    sa.Column('amortizacion', sa.Float(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('seguro_vehicular', sa.Float(), nullable=False),
    sa.Column('seguro_desgravamen', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('es_periodo_gracia', sa.Boolean(), nullable=False),
    sa.Column('es_cuota_balon', sa.Boolean(), nullable=False),
    sa.Column('estado_pago', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['id_credito'], ['creditos_vehiculares.id_credito'], ),
    sa.PrimaryKeyConstraint('id_cuota')
    )
    op.create_index(op.f('ix_cuotas_id_cuota'), 'cuotas', ['id_cuota'], unique=False)
    op.create_table('indicadores_financieros',
    sa.Column('id_indicador', sa.Integer(), nullable=False),
    sa.Column('id_credito', sa.Integer(), nullable=False),
    sa.Column('van', sa.Float(), nullable=False),
    sa.Column('tir_mensual', sa.Float(), nullable=False),
    sa.Column('tcea', sa.Float(), nullable=False),
    sa.Column('total_pagado', sa.Float(), nullable=False),
    sa.Column('total_intereses', sa.Float(), nullable=False),
    sa.Column('costos_adicionales', sa.Float(), nullable=False),
    sa.Column('cuota_balon_monto', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_credito'], ['creditos_vehiculares.id_credito'], ),
    sa.PrimaryKeyConstraint('id_indicador'),
    sa.UniqueConstraint('id_credito')
    )
    op.create_index(op.f('ix_indicadores_financieros_id_indicador'), 'indicadores_financieros', ['id_indicador'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicadores_financieros_id_indicador'), table_name='indicadores_financieros')
    op.drop_table('indicadores_financieros')
    op.drop_index(op.f('ix_cuotas_id_cuota'), table_name='cuotas')
    op.drop_table('cuotas')
    op.drop_index(op.f('ix_creditos_vehiculares_id_credito'), table_name='creditos_vehiculares')
    op.drop_table('creditos_vehiculares')
    op.drop_index(op.f('ix_clientes_id_cliente'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_dni'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_vehiculos_id_vehiculo'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_entidades_financieras_id_entidad'), table_name='entidades_financieras')
    op.drop_table('entidades_financieras')
    # ### end Alembic commands ###
